create extension if not exists pgcrypto;

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text not null,
  location text not null default 'Los Angeles, CA',
  description text,
  salary text,
  salary_min numeric,
  salary_max numeric,
  employment_type text,
  category text,
  seniority_level text,
  apply_url text,
  source_url text,
  source text not null default 'Direct',
  source_id text,
  normalized_key text,
  status text not null default 'active',
  last_seen_date timestamptz,
  posted_date timestamptz,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists jobs_apply_url_unique on public.jobs(apply_url) where apply_url is not null;
create unique index if not exists jobs_normalized_key_unique on public.jobs(normalized_key) where normalized_key is not null;
create unique index if not exists jobs_title_org_unique on public.jobs(title, organization);
create index if not exists jobs_active_created_idx on public.jobs(active, created_at desc);
create index if not exists jobs_source_idx on public.jobs(source);

create table if not exists public.job_submissions (
  id uuid primary key default gen_random_uuid(),
  title text not null, organization text not null, website text, location text not null,
  employment_type text, salary text, description text not null,
  apply_method text not null default 'url' check (apply_method in ('url','email')),
  apply_url text, apply_email text, contact_name text, contact_email text not null,
  contact_phone text, status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  reviewer_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.email_subscriptions (
  id uuid primary key default gen_random_uuid(), email text not null unique,
  frequency text not null default 'Weekly' check (frequency in ('Daily','Weekly','Monthly')),
  keywords text[] not null default '{}', sources text[] not null default '{}',
  locations text[] not null default '{}', active boolean not null default true,
  last_sent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key, name text not null unique,
  website text, careers_url text, ats_type text, location text, city text, county text,
  state text, active boolean not null default true, last_checked timestamptz,
  last_checked_at timestamptz, created_at timestamptz not null default now()
);

create table if not exists public.gmail_tokens (
  id bigint generated by default as identity primary key, email text not null default 'admin', access_token text,
  refresh_token text not null, token_type text, expiry_date bigint, scope text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.processed_emails (
  id bigint generated by default as identity primary key, message_id text not null unique,
  source text, processed_at timestamptz not null default now()
);
create unique index if not exists gmail_tokens_email_unique on public.gmail_tokens(email);

alter table public.jobs enable row level security;
alter table public.job_submissions enable row level security;
alter table public.email_subscriptions enable row level security;
alter table public.organizations enable row level security;
alter table public.gmail_tokens enable row level security;
alter table public.processed_emails enable row level security;

drop policy if exists "Public can read active jobs" on public.jobs;
create policy "Public can read active jobs" on public.jobs for select to anon, authenticated
using (active = true and (expires_at is null or expires_at > now()));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists jobs_set_updated_at on public.jobs;
create trigger jobs_set_updated_at before update on public.jobs for each row execute function public.set_updated_at();
drop trigger if exists submissions_set_updated_at on public.job_submissions;
create trigger submissions_set_updated_at before update on public.job_submissions for each row execute function public.set_updated_at();
drop trigger if exists subscriptions_set_updated_at on public.email_subscriptions;
create trigger subscriptions_set_updated_at before update on public.email_subscriptions for each row execute function public.set_updated_at();

create or replace function public.publish_submission(submission_id uuid)
returns bigint language plpgsql security definer set search_path = public as $$
declare new_job_id bigint;
begin
  insert into public.jobs(title, organization, location, description, salary, employment_type, apply_url, source)
  select title, organization, location, description, salary, employment_type,
    case when apply_method = 'email' then 'mailto:' || apply_email else apply_url end, 'Direct'
  from public.job_submissions where id = submission_id and status <> 'approved'
  returning id into new_job_id;
  if new_job_id is null then raise exception 'Submission not found or already approved'; end if;
  update public.job_submissions set status = 'approved' where id = submission_id;
  return new_job_id;
end $$;
revoke all on function public.publish_submission(uuid) from public, anon, authenticated;

-- Seed rows are optional. Uncomment after setup to verify the UI.
-- insert into public.jobs(title, organization, location, description, source)
-- values ('Program Manager', 'Example Nonprofit', 'Los Angeles, CA', 'Example job description.', 'Direct');
